# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          cd /home/pi/GymPRoof 
          git pull origin main

      - name: Restart System Services
        run: |
          sudo systemctl restart gym_proof.service
